### ISSUE TITLE
ZeroDivisionError when a genome has no fully intergenic sequences

### ISSUE THREAD

**Issue by soi** [weberlab-hhu/GeenuFF#176]
Happens with Olucimarinus and Boleraceacapitata (second is not such a small genome but maybe full of errors)

Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/festi100/git/HelixerPrep/helixerprep/prediction/DanQModel.py", line 190, in <module>
    model.run()
  File "/home/festi100/git/HelixerPrep/helixerprep/prediction/HelixerModel.py", line 381, in run
    self.open_data_files()
  File "/home/festi100/git/HelixerPrep/helixerprep/prediction/HelixerModel.py", line 315, in open_data_files
    n_intergenic_test_seqs / n_test_seqs_with_intergenic * 100))
ZeroDivisionError: division by zero

**Comment by soi** [comment]
Fixed with a warning
