### ISSUE TITLE
Error generating single genome data

### ISSUE THREAD

**Issue by soi** [weberlab-hhu/GeenuFF#270]
Only fails for one genome, both in the 100k and 200k case:

ornithorhynchus_anatinus

6901/10993 Numerified <Coordinate 3891017, seqid: Contig18801, len: 11789> of ornithorhynchus_anatinus with 4 features in 2 chunks, err rate: 25.60%, ig rate: 86.05%, fully err seqs: 0.00% (test)
6902/10993 Numerified <Coordinate 3891018, seqid: Contig16811, len: 11789> of ornithorhynchus_anatinus with 4 features in 2 chunks, err rate: 45.22%, ig rate: 95.22%, fully err seqs: 0.00% (test)Selecting the following genomes: ['ornithorhynchus_anatinus']

6903/10993 Numerified <Coordinate 3891022, seqid: Contig19010, len: 11788> of ornithorhynchus_anatinus with 14 features in 2 chunks, err rate: 45.73%, ig rate: 95.73%, fully err seqs: 0.00% (test)
Traceback (most recent call last):
  File "/home/felix-stiehler/git/HelixerPrep/export.py", line 52, in <module>
    main(args)
  File "/home/felix-stiehler/git/HelixerPrep/export.py", line 17, in main
    val_size=args.val_size, keep_errors=args.keep_errors)
  File "/home/felix-stiehler/git/HelixerPrep/helixerprep/export/exporter.py", line 262, in export
    one_hot)
  File "/home/felix-stiehler/git/HelixerPrep/helixerprep/export/exporter.py", line 226, in _numerify_coord
    one_hot)
  File "/home/felix-stiehler/git/HelixerPrep/helixerprep/export/numerify.py", line 245, in numerify
    labels, label_masks, gene_lengths, transitions = anno_numerifier.coord_to_matrices()
  File "/home/felix-stiehler/git/HelixerPrep/helixerprep/export/numerify.py", line 144, in coord_to_matrices
    minus_strand = self._encode_strand(False)
  File "/home/felix-stiehler/git/HelixerPrep/helixerprep/export/numerify.py", line 153, in _encode_strand
    self._update_matrix_and_error_mask(is_plus_strand=is_plus_strand)
  File "/home/felix-stiehler/git/HelixerPrep/helixerprep/export/numerify.py", line 191, in _update_matrix_and_error_mask
    self.gene_lengths[start:end] = np.maximum(self.gene_lengths[start:end], length_arr)
ValueError: operands could not be broadcast together with shapes (4757,) (4759,)

**Comment by soi** [comment]
Caused by an invalid gff. Will probably just remove the coordinate and its features from the db by hand for now.
