### ISSUE TITLE
Resource allocation problem with ~1.4GB tensor

### ISSUE THREAD

**Issue by soi** [weberlab-hhu/GeenuFF#53]
Is happening with batch size of 64, 64 units and sequence length of 100k. There should be enough space on the 2080 tis.

Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/felix-stiehler/git/HelixerPrep/helixerprep/prediction/LSTMModel.py", line 86, in <module>
    model.run()
  File "/home/felix-stiehler/git/HelixerPrep/helixerprep/prediction/HelixerModel.py", line 214, in run
    verbose=True)
  File "/home/felix-stiehler/src/keras/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/felix-stiehler/src/keras/keras/engine/training.py", line 1658, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/felix-stiehler/src/keras/keras/engine/training_generator.py", line 215, in fit_generator
    class_weight=class_weight)
  File "/home/felix-stiehler/src/keras/keras/engine/training.py", line 1449, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/felix-stiehler/src/keras/keras/backend/tensorflow_backend.py", line 2967, in __call__
    return self._call(inputs)
  File "/home/felix-stiehler/src/keras/keras/backend/tensorflow_backend.py", line 2925, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/felix-stiehler/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/felix-stiehler/venv/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[64,100000,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
 [[{{node cu_dnnlstm_1/transpose_1}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
[[{{node metrics/acc_c/Mean}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by soi** [comment]
Related to that: check what is allocated in the gpu and also how thing are/can be distributed across multiple gpus.

**Comment by soi** [comment]
Not sure if this error is strictly necessary, but given the way RNNs work we are quite constricted with memory when using long sequences. Using multiple gpus works now.
