### ISSUE TITLE
Memory error when calculating kmers for many coordinates

### ISSUE THREAD

**Issue by soi** [weberlab-hhu/GeenuFF#70]
./make_helixer_db.py --db-path-in ~/Desktop/full_geenuff.sqlite3 --min-k 1 --max-k 1
adding the helixer additions directly to input db at /home/felix/Desktop/full_geenuff.sqlite3

kmers added: 10000/252106
kmers added: 20000/252106
kmers added: 30000/252106
kmers added: 40000/252106
kmers added: 50000/252106
kmers added: 60000/252106
kmers added: 70000/252106

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 431, in _handle_workers
    maxtasksperchild, wrap_exception)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 268, in _maintain_pool
    wrap_exception)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 255, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 489, in _handle_results
    task = get()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 411, in _recv_bytes
    return self._recv(size)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 386, in _recv
    buf.write(chunk)
MemoryError

**Comment by soi** [comment]
Should be fixed by lowering the limit of coordinates to load in memory at once to 1000 instead 10000
